Archetype/danceability
cis3296s24/02-SpotiFynd pull request #21
Opened 2024-04-02 20:15 UTC by tun51789

2024-04-03 13:58 UTC, tuo20482 commented on df.html
We shouldn't add the output file to git. The other two files are good though.

2024-04-03 13:59 UTC, tuo20482 requested changes
Take out the df.html and the other two are good

2024-04-04 14:32 UTC, MatthewChristofas approved these changes
Looks good.

2024-04-04 14:38 UTC, tuo20482 approved these changes

2024-04-04 14:39 UTC, merged